// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../mocks/service_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "comment-tree/internal/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCommentsRepository is a mock of CommentsRepository interface.
type MockCommentsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCommentsRepositoryMockRecorder
	isgomock struct{}
}

// MockCommentsRepositoryMockRecorder is the mock recorder for MockCommentsRepository.
type MockCommentsRepositoryMockRecorder struct {
	mock *MockCommentsRepository
}

// NewMockCommentsRepository creates a new mock instance.
func NewMockCommentsRepository(ctrl *gomock.Controller) *MockCommentsRepository {
	mock := &MockCommentsRepository{ctrl: ctrl}
	mock.recorder = &MockCommentsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentsRepository) EXPECT() *MockCommentsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommentsRepository) Create(ctx context.Context, com *models.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, com)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCommentsRepositoryMockRecorder) Create(ctx, com any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommentsRepository)(nil).Create), ctx, com)
}

// Delete mocks base method.
func (m *MockCommentsRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommentsRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommentsRepository)(nil).Delete), ctx, id)
}

// GetByParent mocks base method.
func (m *MockCommentsRepository) GetByParent(ctx context.Context, parentID *int64, limit, offset int64) ([]*models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByParent", ctx, parentID, limit, offset)
	ret0, _ := ret[0].([]*models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByParent indicates an expected call of GetByParent.
func (mr *MockCommentsRepositoryMockRecorder) GetByParent(ctx, parentID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByParent", reflect.TypeOf((*MockCommentsRepository)(nil).GetByParent), ctx, parentID, limit, offset)
}

// Search mocks base method.
func (m *MockCommentsRepository) Search(ctx context.Context, query string, limit, offset int64) ([]*models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, limit, offset)
	ret0, _ := ret[0].([]*models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockCommentsRepositoryMockRecorder) Search(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockCommentsRepository)(nil).Search), ctx, query, limit, offset)
}

// Update mocks base method.
func (m *MockCommentsRepository) Update(ctx context.Context, com *models.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, com)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCommentsRepositoryMockRecorder) Update(ctx, com any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommentsRepository)(nil).Update), ctx, com)
}
